name: Bradley Leese
favicon: null
layout_spectrum: 0.42667
typography_spectrum: 0.52041
title: Bradley Leese - Family Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eed300'
    - '#c08600'
    - '#65926b'
    - '#365939'
    - '#703400'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
