name: Bradley Leese
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52041
title: Bradley Leese - Family Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#699af7'
    - '#a2ceff'
    - '#494529'
    - '#82912f'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
