name: BradleyLeese
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7376747725065798
title: Bradley Leese - Family Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#699af7'
    - '#a2ceff'
    - '#494529'
    - '#82912f'
  brandStrength: 0.6216197214089334
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
