analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.32407
title: Bradley Leese - Family Journal
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#eed300'
    - '#c08600'
    - '#65926b'
    - '#365939'
    - '#703400'
  lightness: 0.3125
purpose: []
favicon: null
name: Bradley Leese
typography_spectrum: 0.52041
