layout_spectrum: 0.1644317941647023
typography_spectrum: 0.2840135959711959
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.8143884950441005
  lightness: 0.7861284692722862
  saturation: 0.30325607710822233
  rhythmicContrast: 0.3682835127959157
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-9530598-13
  facebook: null
  twitter: null
name: Bradley Leese
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Bradley Leese
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/27cf34be-4dde-46cc-8e71-e2e62857b076.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/27cf34be-4dde-46cc-8e71-e2e62857b076.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: contact
    url: 'tel:8184259733'
    label: Call 8184259733
  - type: contact
    url: 'mailto:bradleyleese@gmail.com'
    label: Email Me
description: Identity visionary
content_rating:
  adult: false
author:
  name: Bradley Leese
  email: bradleyleese@gmail.com
  url: 'http://www.bradleyleese.com'
