name: Bradley Leese
favicon: null
layout_spectrum: 0.7575
typography_spectrum: 0.79509
title: 'Stepping Back & Looking Forward - Bradley'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f79c82'
    - '#505a78'
    - '#7fde95'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
