layout_spectrum: 0.4893818475160342
typography_spectrum: 0.5543121618310931
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.5027169854343306
  lightness: 0.8287608230752077
  saturation: 0.9204033726123669
  rhythmicContrast: 0.5348255265694997
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-9530598-13
  facebook: null
  twitter: null
name: Bradley Leese
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Bradley Leese
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/27cf34be-4dde-46cc-8e71-e2e62857b076.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/27cf34be-4dde-46cc-8e71-e2e62857b076.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: contact
    url: 'tel:8184259733'
    label: Call 8184259733
  - type: contact
    url: 'mailto:bradleyleese@gmail.com'
    label: Email Me
description: Identity visionary
content_rating:
  adult: false
author:
  name: Bradley Leese
  email: bradleyleese@gmail.com
  url: 'http://www.bradleyleese.com'
